apiVersion: apps/v1
kind: Deployment
metadata:
  name: NM
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NM
  template:
    metadata:
      labels:
        app: NM
    spec:
      containers:
      - image: okteto.dev/NM:latest
        name: NM
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0ea8a43c-bbfd-4069-bfe8-d312bbc3bfff"
        - name: Vless_Path
          value: "/vlefefe"
        - name: Vmess_UUID
          value: "0ea8a43c-bbfd-4069-bfe8-d312bbc3bfff"
        - name: Vmess_Path
          value: "/vm6errrh"
        - name: Share_Path
          value: "/v2link"
